<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'E-mail per ricevere la notifica della distruzione della nota.',
    'Введите код' => 'Inserisci un codice',
    'Введите пароль' => 'inserire la password',
    'Для доступа необходим пароль' => 'Password richiesta per accedere',
    'Записка самоуничтожится' => 'La nota si autodistruggerà',
    'Использовать' => 'Uso',
    'Использовать код' => 'Usa il codice',
    'Код введен не верно.' => 'Il codice è stato inserito in modo errato.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Fare clic per copiare la linea negli Appunti',
    'Настроить' => 'Sintonizzare',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Il servizio online Private Service ti consente di inviare messaggi, che verranno automaticamente distrutti dopo averli letti. È impossibile ripristinare una simile lettera.',
    'Отправить' => 'Invia',
    'Ошибка!' => 'Sbaglio!',
    'Пароль' => 'Parola d\'ordine',
    'Пароль(необязательно)' => 'Password (opzionale)',
    'Пишите ваше сообщение здесь...' => 'Scrivi qui il tuo messaggio ...',
    'Повторите пароль' => 'Conferma password',
    'Пользователь' => 'Utente',
    'Приватные сообщения' => 'Messaggi privati',
    'Прикрепите изображение' => 'Allega un\'immagine',
    'Просмотр записки №' => 'Vedi nota #',
    'Просмотр чата №' => 'Visualizza la chat n.',
    'Сервис приватных сообщений' => 'Servizio di messaggistica privata',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Crea carte usa e getta e chat con completo anonimato.',
    'Создать еще одну.' => 'Creane un altro.',
    'Создать секретный чат' => 'Crea una chat segreta',
    'Создать сообщение' => 'Creare un messaggio',
    'Создать чат' => 'Crea chat',
    'Тут ваш код.' => 'Ecco il tuo codice',
    'Тут ваша ссылка.' => 'Ecco il tuo link',
    'Чат №' => 'Chiacchierare #',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'servizio personale, chat sicura, chat crittografata, note sicure, nota privata, nota privata, nota condivisa, file condiviso, note crittografate, tecnologia infinita, autodistruzione, note autodistruzione, file autodistruzione, note sicure, file crittografati, note crittografate, invio crittografato',
    'подключился к чату' => 'collegato alla chat',
    'после прочтения' => 'dopo aver letto',
    'спустя 1 час' => 'dopo 1 ora',
    'спустя 24 часа' => 'dopo 24 ore',
    'спустя 30 дней' => 'dopo 30 giorni',
    'спустя 7 дней' => 'dopo 7 giorni',
    'ушел из чата' => 'lasciato la chat',
];
