<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => '',
    'Введите код' => '',
    'Введите пароль' => '',
    'Для доступа необходим пароль' => '',
    'Записка самоуничтожится' => '',
    'Использовать' => '',
    'Использовать код' => '',
    'Код введен не верно.' => '',
    'Нажмите, чтобы скопировать строку в буфер обмена' => '',
    'Настроить' => '',
    'Отправить' => '',
    'Ошибка!' => '',
    'Пароль' => '',
    'Пароль(необязательно)' => '',
    'Пишите ваше сообщение здесь...' => '',
    'Повторите пароль' => '',
    'Пользователь' => '',
    'Приватные сообщения' => '',
    'Прикрепите изображение' => '',
    'Сервис приватных сообщений' => '',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => '',
    'Создать еще одну.' => '',
    'Создать секретный чат' => '',
    'Создать сообщение' => '',
    'Создать чат' => '',
    'Тут ваш код.' => '',
    'Тут ваша ссылка.' => '',
    'Чат №' => '',
    'подключился к чату' => '',
    'после прочтения' => '',
    'спустя 1 час' => '',
    'спустя 24 часа' => '',
    'спустя 30 дней' => '',
    'спустя 7 дней' => '',
    'ушел из чата' => '',
];
