<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'E-mail s upozornením o zničení bankovky.',
    'Введите код' => 'Zadajte kód',
    'Введите пароль' => 'Zadajte heslo',
    'Для доступа необходим пароль' => 'Na prístup je potrebné heslo',
    'Записка самоуничтожится' => 'Poznámka sa zničí',
    'Использовать' => 'použitie',
    'Использовать код' => 'Použite kód',
    'Код введен не верно.' => 'Kód bol zadaný nesprávne.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Kliknutím skopírujete riadok do schránky',
    'Настроить' => 'melódie',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Online služba Private Service vám umožňuje odosielať správy, ktoré sa po prečítaní automaticky zničia. Nie je možné takýto list obnoviť.',
    'Отправить' => 'Predložiť',
    'Ошибка!' => 'Chyba!',
    'Пароль' => 'heslo',
    'Пароль(необязательно)' => 'Heslo (voliteľné)',
    'Пишите ваше сообщение здесь...' => 'Sem napíš svoju správu ...',
    'Повторите пароль' => 'Potvrďte heslo',
    'Пользователь' => 'užívateľ',
    'Приватные сообщения' => 'Súkromné ​​správy',
    'Прикрепите изображение' => 'Pripojte obrázok',
    'Просмотр записки №' => 'Zobraziť poznámku č.',
    'Просмотр чата №' => 'Zobraziť číslo četu',
    'Сервис приватных сообщений' => 'Súkromná služba správ',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Vytvorte jednorazové karty a rozhovory s úplnou anonymitou.',
    'Создать еще одну.' => 'Vytvorte ďalšie.',
    'Создать секретный чат' => 'Vytvorte tajný rozhovor',
    'Создать сообщение' => 'Vytvoriť správu',
    'Создать чат' => 'Vytvoriť chat',
    'Тут ваш код.' => 'Tu je váš kód.',
    'Тут ваша ссылка.' => 'Tu je váš odkaz.',
    'Чат №' => 'Č. Č.',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'osobná služba, bezpečný chat, šifrovaný chat, bezpečné noty, súkromná nota, súkromná nota, zdieľaná nota, zdieľaný súbor, šifrované noty, nekonečná technológia, sebazničenie, samodestrukovacie poznámky, samodestrukujúci súbor, bezpečné notifikácie, šifrované súbory, šifrované noty, šifrované odosielanie',
    'подключился к чату' => 'pripojený k chatu',
    'после прочтения' => 'po prečítaní',
    'спустя 1 час' => 'po 1 hodine',
    'спустя 24 часа' => 'po 24 hodinách',
    'спустя 30 дней' => 'po 30 dňoch',
    'спустя 7 дней' => 'po 7 dňoch',
    'ушел из чата' => 'opustil chat',
];
