<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'Correo electrónico para recibir notificación de la destrucción de la nota.',
    'Введите код' => 'Ingrese un código',
    'Введите пароль' => 'introducir la contraseña',
    'Для доступа необходим пароль' => 'Contraseña requerida para acceder',
    'Записка самоуничтожится' => 'La nota se autodestruirá',
    'Использовать' => 'Utilizar',
    'Использовать код' => 'Usar código',
    'Код введен не верно.' => 'El código fue ingresado incorrectamente.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Haga clic para copiar la línea al portapapeles',
    'Настроить' => 'Melodía',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'El servicio en línea Private Service le permite enviar mensajes, que se destruirán automáticamente después de leerlos. Es imposible restaurar una carta así.',
    'Отправить' => 'Enviar',
    'Ошибка!' => '¡Error!',
    'Пароль' => 'Contraseña',
    'Пароль(необязательно)' => 'Contraseña (opcional)',
    'Пишите ваше сообщение здесь...' => 'Escriba su mensaje aquí ...',
    'Повторите пароль' => 'Confirmar contraseña',
    'Пользователь' => 'Usuario',
    'Приватные сообщения' => 'Mensajes privados',
    'Прикрепите изображение' => 'Adjunta una imagen',
    'Просмотр записки №' => 'Ver nota #',
    'Просмотр чата №' => 'Ver Chat No.',
    'Сервис приватных сообщений' => 'Servicio de mensajería privada',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Crea tarjetas y chats desechables con completo anonimato.',
    'Создать еще одну.' => 'Crea otro.',
    'Создать секретный чат' => 'Crea un chat secreto',
    'Создать сообщение' => 'Crear un mensaje',
    'Создать чат' => 'Crear chat',
    'Тут ваш код.' => 'Aquí está tu código.',
    'Тут ваша ссылка.' => 'Aquí está tu enlace.',
    'Чат №' => 'Chat #',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'servicio personal, chat seguro, chat encriptado, notas seguras, nota privada, nota privada, compartir nota, compartir archivo, notas cifradas, tecnología infinita, autodestrucción, notas de autodestrucción, archivo de autodestrucción, notas seguras, archivos cifrados, notas cifradas, enviar cifrado',
    'подключился к чату' => 'conectado al chat',
    'после прочтения' => 'despues de leer',
    'спустя 1 час' => 'después de 1 hora',
    'спустя 24 часа' => 'después de 24 horas',
    'спустя 30 дней' => 'después de 30 días',
    'спустя 7 дней' => 'después de 7 días',
    'ушел из чата' => 'dejó la conversación',
];
