<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'E-Mail, um eine Benachrichtigung über die Zerstörung der Notiz zu erhalten.',
    'Введите код' => 'Geben Sie einen Code ein',
    'Введите пароль' => 'Passwort eingeben',
    'Для доступа необходим пароль' => 'Für den Zugriff ist ein Passwort erforderlich',
    'Записка самоуничтожится' => 'Die Notiz wird sich selbst zerstören',
    'Использовать' => 'Verwenden',
    'Использовать код' => 'Verwenden Sie Code',
    'Код введен не верно.' => 'Der Code wurde falsch eingegeben.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Klicken Sie hier, um die Zeile in die Zwischenablage zu kopieren',
    'Настроить' => 'Melodie',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Mit dem Onlinedienst Private Service können Sie Nachrichten senden, die nach dem Lesen automatisch zerstört werden. Es ist unmöglich, einen solchen Brief wiederherzustellen.',
    'Отправить' => 'Nachricht senden',
    'Ошибка!' => 'Fehler!',
    'Пароль' => 'Passwort',
    'Пароль(необязательно)' => 'Passwort (optional)',
    'Пишите ваше сообщение здесь...' => 'Schreibe deine Nachricht hier ...',
    'Повторите пароль' => 'Wiederholen Sie das Passwort',
    'Пользователь' => 'Benutzer',
    'Приватные сообщения' => 'Private Nachrichten',
    'Прикрепите изображение' => 'Fügen Sie ein Bild hinzu',
    'Просмотр записки №' => 'Hinweis anzeigen #',
    'Просмотр чата №' => 'Chat-Nr. Anzeigen',
    'Сервис приватных сообщений' => 'Privater Nachrichtendienst',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Erstellen Sie Einwegkarten und Chats mit vollständiger Anonymität.',
    'Создать еще одну.' => 'Erstellen Sie eine andere.',
    'Создать секретный чат' => 'Erstelle einen geheimen Chat',
    'Создать сообщение' => 'Nachricht erstellen',
    'Создать чат' => 'Chat erstellen',
    'Тут ваш код.' => 'Hier ist dein Code.',
    'Тут ваша ссылка.' => 'Hier ist dein Link.',
    'Чат №' => 'Plaudern #',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'Persönlicher Service, sicherer Chat, verschlüsselter Chat, sichere Notizen, private Notiz, private Notiz, Notiz teilen, Datei teilen, verschlüsselte Notizen, unendliche Technologie, Selbstzerstörung, Selbstzerstörungsnotizen, Selbstzerstörungsdatei, sichere Notizen, verschlüsselte Dateien, verschlüsselte Notizen, verschlüsselt senden',
    'подключился к чату' => 'mit dem Chat verbunden',
    'после прочтения' => 'nach dem Lesen',
    'спустя 1 час' => 'nach 1 Stunde',
    'спустя 24 часа' => 'nach 24 Stunden',
    'спустя 30 дней' => 'nach 30 Tagen',
    'спустя 7 дней' => 'nach 7 Tagen',
    'ушел из чата' => 'verließ den Chat',
];
