<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'E-Mail, um eine Benachrichtigung über die Zerstörung der Notiz zu erhalten.',
    'Введите код' => '',
    'Введите пароль' => '',
    'Для доступа необходим пароль' => '',
    'Записка самоуничтожится' => '',
    'Использовать' => '',
    'Использовать код' => '',
    'Код введен не верно.' => '',
    'Нажмите, чтобы скопировать строку в буфер обмена' => '',
    'Настроить' => '',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Mit dem Onlinedienst Private Service können Sie Nachrichten senden, die nach dem Lesen automatisch zerstört werden. Es ist unmöglich, einen solchen Brief wiederherzustellen.',
    'Отправить' => '',
    'Ошибка!' => '',
    'Пароль' => '',
    'Пароль(необязательно)' => '',
    'Пишите ваше сообщение здесь...' => '',
    'Повторите пароль' => '',
    'Пользователь' => '',
    'Приватные сообщения' => 'Private Nachrichten',
    'Прикрепите изображение' => '',
    'Просмотр записки №' => '',
    'Просмотр чата №' => '',
    'Сервис приватных сообщений' => 'Privater Nachrichtendienst',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Erstellen Sie Einwegkarten und Chats mit vollständiger Anonymität.',
    'Создать еще одну.' => '',
    'Создать секретный чат' => '',
    'Создать сообщение' => '',
    'Создать чат' => '',
    'Тут ваш код.' => '',
    'Тут ваша ссылка.' => '',
    'Чат №' => '',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'Persönlicher Service, sicherer Chat, verschlüsselter Chat, sichere Notizen, private Notiz, private Notiz, Notiz teilen, Datei teilen, verschlüsselte Notizen, unendliche Technologie, Selbstzerstörung, Selbstzerstörungsnotizen, Selbstzerstörungsdatei, sichere Notizen, verschlüsselte Dateien, verschlüsselte Notizen, verschlüsselt senden',
    'подключился к чату' => '',
    'после прочтения' => '',
    'спустя 1 час' => '',
    'спустя 24 часа' => '',
    'спустя 30 дней' => '',
    'спустя 7 дней' => '',
    'ушел из чата' => '',
];
