<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'private service, secure chat, encrypted chat, safe notes, privatenote, private note, share note, share file, encrypted notes, infinitum tech, self-destruct, self-destruct notes, self-destruct file, secure notes, encrypted files, encrypted notes, send encrypt',
    'E-mail для получения уведомления об уничтожении записки.' => 'E-mail to receive notification of the destruction of the note.',
    'Введите код' => 'Enter code',
    'Введите пароль' => 'Enter password',
    'Для доступа необходим пароль' => 'A password is required to access',
    'Записка самоуничтожится' => 'The note will self-destruct',
    'Использовать' => 'Go',
    'Использовать код' => 'Use code',
    'Код введен не верно.' => 'The code was entered incorrectly.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Click to copy the line to the clipboard',
    'Настроить' => 'Settings',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Online service Private Service allows you to send messages that will be automatically deleted after reading them. It is impossible to recover such a message.',
    'Отправить' => 'Send',
    'Ошибка!' => 'Error!',
    'Пароль' => 'Password',
    'Пароль(необязательно)' => 'Password (optional)',
    'Пишите ваше сообщение здесь...' => 'Write your message here ...',
    'Повторите пароль' => 'Repeat your password',
    'Пользователь' => 'User',
    'Приватные сообщения' => 'Private service',
    'Прикрепите изображение' => 'Attach Image',
    'Просмотр записки №' => 'View note #',
    'Просмотр чата №' => 'View chat #',
    'Сервис приватных сообщений' => 'Private messaging service',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Create disposable cards and chats with complete anonymity.',
    'Создать еще одну.' => 'Create another one.',
    'Создать секретный чат' => 'Create secret chat',
    'Создать сообщение' => 'Create message',
    'Создать чат' => 'Create chat',
    'Тут ваш код.' => 'This is your code.',
    'Тут ваша ссылка.' => 'Here is your link.',
    'Чат №' => 'Chat #',
    'подключился к чату' => 'connected to chat',
    'после прочтения' => 'after reading',
    'спустя 1 час' => 'after 1 hour',
    'спустя 24 часа' => 'after 24 hours',
    'спустя 30 дней' => 'after 30 days',
    'спустя 7 дней' => 'after 7 days',
    'ушел из чата' => 'left the chat',
];
