<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail для получения уведомления об уничтожении записки.' => 'E-mail pentru a primi notificarea distrugerii notei.',
    'Введите код' => 'Introduceți un cod',
    'Введите пароль' => 'Introdu parola',
    'Для доступа необходим пароль' => 'Parola necesară pentru a accesa',
    'Записка самоуничтожится' => 'Nota se va autodistruge',
    'Использовать' => 'Utilizare',
    'Использовать код' => 'Utilizați codul',
    'Код введен не верно.' => 'Codul a fost introdus incorect.',
    'Нажмите, чтобы скопировать строку в буфер обмена' => 'Faceți clic pentru a copia linia în clipboard',
    'Настроить' => 'Ton',
    'Онлайн-сервис Private Service позволяет отправлять сообщения, которые будут автоматически уничтожены после их прочтения. Восстановить такое письмо невозможно.' => 'Serviciul online Serviciu privat vă permite să trimiteți mesaje, care vor fi distruse automat după ce vor fi citite. Este imposibil să restaurați o astfel de scrisoare.',
    'Отправить' => 'Trimite',
    'Ошибка!' => 'Greşeală!',
    'Пароль' => 'Parola',
    'Пароль(необязательно)' => 'Parolă (opțional)',
    'Пишите ваше сообщение здесь...' => 'Scrie mesajul tău aici ...',
    'Повторите пароль' => 'Confirmă parola',
    'Пользователь' => 'Utilizator',
    'Приватные сообщения' => 'Mesaje private',
    'Прикрепите изображение' => 'Atașați o imagine',
    'Просмотр записки №' => 'Vezi nota #',
    'Просмотр чата №' => 'Vezi nr de chat',
    'Сервис приватных сообщений' => 'Serviciu privat de mesagerie',
    'Создавайте одноразовые открытки и чаты с полной анонимностью.' => 'Creați cărți și chaturi de unică folosință cu un anonimat complet.',
    'Создать еще одну.' => 'Creați altul.',
    'Создать секретный чат' => 'Creați un chat secret',
    'Создать сообщение' => 'Creare mesaj',
    'Создать чат' => 'Creați chat',
    'Тут ваш код.' => 'Iată codul tău.',
    'Тут ваша ссылка.' => 'Iată linkul tău.',
    'Чат №' => 'Conversație #',
    'личная служба, безопасный чат, зашифрованный чат, безопасные заметки, приватная заметка, личная заметка, поделиться заметкой, поделиться файлом, зашифрованные заметки, бесконечная технология, самоуничтожение, заметки самоуничтожения, файл самоуничтожения, безопасные заметки, зашифрованные файлы, зашифрованные заметки, отправить зашифрованный' => 'servicii personale, chat securizat, chat criptat, note sigure, notă privată, notă privată, notă de partajare, fișier de partajare, note criptate, tehnologie nesfârșită, autodistrugere, note de autodistrugere, fișier de autodistrugere, note sigure, fișiere criptate, note criptate, trimitere criptată',
    'подключился к чату' => 'conectat la chat',
    'после прочтения' => 'dupa citit',
    'спустя 1 час' => 'după 1 oră',
    'спустя 24 часа' => 'după 24 de ore',
    'спустя 30 дней' => 'după 30 de zile',
    'спустя 7 дней' => 'după 7 zile',
    'ушел из чата' => 'a părăsit conversația',
];
